language: go

go:
  - master

script:
  - ./run_test.sh

after_success:
  - include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      secure: "jQ6nLHe5F4G9wv/XfK48THI49LzZgSFsfvGe2OpM3DN+1khcxndVvh8V+CSMufiNtmrME2VEO27KIjH9Evd77cAPvXgJZiBwgaXDQk3Lx0isxcE62HNXXbtSKu6vZCNZAQ+3HZlzGLDhU6UAv6x97neT2kzc2qbq560m1DgtDkJ56DSjfKcrOBHjVVqZCr35+lbd2ssnBEPo5kH1h/9iQje7bv+9yEVhGvMjRTFCpXBsfKisVYUe5Z+2AoqHoI1ztXMFIrcFBikgaZhPNqbpkPoGIQWSpUMNwvfCIyUB5O4nqhAEaZPjxs/lAsZwH1SoiELN/1mEfs7ZaZSmrHOR0Hv/IWVVLTDq6GmgVqrJmuaH0PHzEzT/ra+9bOQowDkzV6f90FsPolpC3Ne4FzQ+krnPDZJavVxBDppwoRjTcWlusm4kKCs5fpCFNGwAHOdCG0jWy3+moY9AgpAXKTsvhmKSnNI6zFbgOQVHr140b4UCkxU9xv+gOxL2h86Q9AOuhmAWFOkB9iJVivwwJ4uf26d56bZTKBP/PjNX5V3HlOTvy3GM/ra+6pwBDbcHB2EPmFOuPCSDLqhvWe8uiCPTX3/gDfLrsXhF10WSE9m0h6esRTqknoNEv2CqFp2y50BtF22EEhtkPBK98mBYVA5yehBiBPGAIiN0ekXQwBtIEpg="
    on_success: change
    on_failure: always
